name: Build and Test Code

on:
  workflow_dispatch:
  push:
    paths:
      - "projects/**"
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

env:
  SOLUTION_FOLDER: "projects"

jobs:
  deploy:
    name: Build and Test Code
    runs-on: windows-latest
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v2
      - name: âœ¨ Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
      - name: ğŸšš Restore
        run: dotnet restore ${{ env.SOLUTION_FOLDER }}
      - name: ğŸ› ï¸ Build
        run: dotnet build ${{ env.SOLUTION_FOLDER }} --configuration Release --no-restore
      - name: ğŸ§ª Test
        run: dotnet test ${{ env.SOLUTION_FOLDER }} --configuration Release --no-restore --verbosity normal
