name: Site

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: ğŸš€ Generate and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v2

      - name: âœ¨ Set up .NET
        uses: actions/setup-dotnet@v1

      - name: ğŸ› ï¸ SiteBuilder
        working-directory: dev/SiteBuilder
        run: dotnet build

      - name: ğŸŒ Generate Website
        working-directory: dev/SiteBuilder
        run: dotnet run

      - name: ğŸš€ Deploy
        uses: SamKirkland/FTP-Deploy-Action@65c6a8f943bbf04faf9b59520a103318b418952e # 4.1.0
        with:
          local-dir: content/
          server-dir: /maui.graphics/public_html
          protocol: ftps
          server: maui.graphics
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          log-level: minimal