name: Site

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: ğŸš€ Generate and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v2

      - name: âœ¨ Set up .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"

      - name: ğŸšš NuGet Restore
        run: dotnet restore dev/SiteBuilder

      - name: ğŸ› ï¸ Build SiteBuilder
        run: dotnet build dev/SiteBuilder --no-restore

      - name: ğŸŒ Generate Website
        run: dotnet run --project dev/SiteBuilder

      - name: ğŸš€ Deploy
        uses: SamKirkland/FTP-Deploy-Action@65c6a8f943bbf04faf9b59520a103318b418952e # 4.1.0
        with:
          local-dir: /content/
          server-dir: /
          protocol: ftps
          server: maui.graphics
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          log-level: minimal